### ISSUE TITLE
Resources not being loaded for Demo

### ISSUE THREAD

**Issue by EvanBurbidge** [matsbryntse/gridsplit#1]
Hey trying to work with your Demo and have found that all the requests seem to be getting rejected. I've attached an image of my console. 

![screen shot 2017-08-08 at 10 24 14](https://user-images.githubusercontent.com/10980413/29062907-e0d23d40-7c23-11e7-8201-11eb0c8f703a.png)

**Comment by matsbryntse** [comment]
Fixed now, thanks for the report!
